apiVersion: v1
kind: Pod
metadata:
  name: cm-secret-pod
  labels:
    manager: chris
spec:
  containers:
    - name: db
      image: registry.fedoraproject.org/f32/mysql:latest
      ports:
        - containerPort: 3306
          protocol: TCP
      env:
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: cm-cisco
              key: user
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: cm-cisco
              key: database

        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-cisco
              key: password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-cisco
              key: root_password
