apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: project-request
objects:
- apiVersion: project.openshift.io/v1
  kind: Project
  metadata:
    annotations:
      openshift.io/description: ${PROJECT_DESCRIPTION}
      openshift.io/display-name: ${PROJECT_DISPLAYNAME}
      openshift.io/requester: ${PROJECT_REQUESTING_USER}
    creationTimestamp: null
    name: ${PROJECT_NAME}
  spec: {}
  status: {}

- apiVersion: v1
  kind: Pod
  metadata:
    name: ${PROJECT_NAME}-pod
    labels:
      app: ${PROJECT_NAME}-pod-default
  spec:
    containers:
      - name: web
        image: registry.access.redhat.com/ubi9/httpd-24:9.7
        ports:
          - containerPort: 8080
          - containerPort: 8443

- apiVersion: v1
  kind: ResourceQuota
  metadata:
    creationTimestamp: null
    name: ${PROJECT_NAME}-compute-quota
  spec:
    hard:
      limits.cpu: 30m
      limits.memory: 40Mi
      requests.cpu: 10m
      requests.memory: 20Mi
  status: {}

- apiVersion: v1
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    name: ${PROJECT_NAME}-cm-cisco
  data:
    database: cisco
    user: chris

- apiVersion: v1
  kind: Secret
  metadata:
    creationTimestamp: null
    name: ${PROJECT_NAME}-secret-cisco
  data:
    password: bXlwYTU1
    root_password: cjAwdHBhNTU=

- apiVersion: v1
  kind: ResourceQuota
  metadata:
    creationTimestamp: null
    name: count-quota
  spec:
    hard:
      count/configmaps: "4"
      count/deployments.apps: "2"
      count/pods: "6"
      count/routes.route.openshift.io: "2"
      count/secrets: "6"
      count/services: "2"
  status: {}

- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: admin
    namespace: ${PROJECT_NAME}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: admin
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: ${PROJECT_ADMIN_USER}
parameters:
- name: PROJECT_NAME
- name: PROJECT_DISPLAYNAME
- name: PROJECT_DESCRIPTION
- name: PROJECT_ADMIN_USER
- name: PROJECT_REQUESTING_USER
