---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cisco
  name: cisco-app
spec:
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: 8080
  selector:
    manager: chris
status:
  loadBalancer: {}
