apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
  - route.yml
  - service.yml
 
configMapGenerator:
  - name: cm-cisco
    literals:
      - user=kartik
      - database=raleigh


secretGenerator:
  - name: secret-cisco
    literals:
      - password=SomePass123
      - root_password=AnotherRoot123
